=== RGReeTy/ParsingXMLByDifferentMethods/web/WEB-INF/resources/touristVouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="touristVouchers" type="touristVouchers"/>
    <xsd:complexType name="touristVouchers">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="touristVoucher" type="touristVoucher"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="touristVoucher">
        <xsd:sequence>
            <xsd:element name="type" type="type"/>
            <xsd:element name="country" type="countryString"/>
            <xsd:element name="startDate" type="xsd:date"/>
            <xsd:element name="numberDaysNights" type="xsd:positiveInteger"/>
            <xsd:element name="transport" type="transport"/>
            <xsd:element name="hotelSpecification" type="hotelSpecification"/>
            <xsd:element name="price" type="xsd:decimal"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="countryString">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-Z][A-Za-z\s]+)"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="hotelSpecification">
        <xsd:sequence>
            <xsd:element name="stars" type="max5Positive"/>
            <xsd:element name="meals" type="meal"/>
            <xsd:element name="numberOfRooms" type="max5Positive"/>
            <xsd:element name="airCondition" type="xsd:boolean"/>
            <xsd:element name="tv" type="xsd:boolean"/>
            <xsd:element name="wifi" type="xsd:boolean"/>
            <xsd:element name="parking" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="max5Positive">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:maxInclusive value="5"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="meal">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="HB"/>
            <xsd:enumeration value="BB"/>
            <xsd:enumeration value="AI"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="WEEKEND"/>
            <xsd:enumeration value="TOUR"/>
            <xsd:enumeration value="RELAXATION"/>
            <xsd:enumeration value="PILGRIMAGE"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="transport">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="AIR"/>
            <xsd:enumeration value="BUS"/>
            <xsd:enumeration value="TRAIN"/>
            <xsd:enumeration value="CAR"/>
            <xsd:enumeration value="LINER"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== RGReeTy/ParsingXMLByDifferentMethods/src/main/resources/delete/touristVouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<touristVouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="touristVouchers.xsd">
    <touristVoucher id="czech1">
        <type>WEEKEND</type>
        <country>Czech Republic</country>
        <startDate>2020-02-25</startDate>
        <numberDaysNights>3</numberDaysNights>
        <transport>BUS</transport>
        <hotelSpecification>
            <stars>3</stars>
            <meals>HB</meals>
            <numberOfRooms>1</numberOfRooms>
            <airCondition>true</airCondition>
            <tv>true</tv>
            <wifi>true</wifi>
            <parking>false</parking>
        </hotelSpecification>
        <price>300.00</price>
    </touristVoucher>
    <touristVoucher id="usa1">
        <type>RELAXATION</type>
        <country>USA</country>
        <startDate>2020-05-09</startDate>
        <numberDaysNights>30</numberDaysNights>
        <transport>AIR</transport>
        <hotelSpecification>
            <stars>4</stars>
            <meals>AI</meals>
            <numberOfRooms>2</numberOfRooms>
            <airCondition>true</airCondition>
            <tv>true</tv>
            <wifi>true</wifi>
            <parking>false</parking>
        </hotelSpecification>
        <price>6000.00</price>
    </touristVoucher>
    <touristVoucher id="isr1">
        <type>PILGRIMAGE</type>
        <country>Israel</country>
        <startDate>2020-03-01</startDate>
        <numberDaysNights>14</numberDaysNights>
        <transport>BUS</transport>
        <hotelSpecification>
            <stars>2</stars>
            <meals>HB</meals>
            <numberOfRooms>1</numberOfRooms>
            <airCondition>false</airCondition>
            <tv>false</tv>
            <wifi>false</wifi>
            <parking>false</parking>
        </hotelSpecification>
        <price>2000.00</price>
    </touristVoucher>
    <touristVoucher id="SA4">
        <type>PILGRIMAGE</type>
        <country>India</country>
        <startDate>2020-08-09</startDate>
        <numberDaysNights>21</numberDaysNights>
        <transport>AIR</transport>
        <hotelSpecification>
            <stars>5</stars>
            <meals>AI</meals>
            <numberOfRooms>3</numberOfRooms>
            <airCondition>true</airCondition>
            <tv>true</tv>
            <wifi>true</wifi>
            <parking>true</parking>
        </hotelSpecification>
        <price>3250.00</price>
    </touristVoucher>
</touristVouchers>
